apiVersion: v1
kind: Service
metadata:
  name: roar-web
  labels:
    name: roar-web
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 8089
    targetPort: 8080
  selector:
    name: roar-web
